version: "3"
services:
  mongo:
    container_name: "database"
    image: "mongo"
    ports:
      - "27017:27017"

  fastapi-app:
    container_name: "fastapi-app"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo